id: b66d0e40086c49cfb5e3e545b14b5644
initial_creation_type: ebook
created_at: 8/04/2021
last_modified_at: 25/11/2021
source_metadata:
  title: test
  subtitle: ''
  authors:
  - test
  collection: ''
  publisher: ''
  id: q23423
  cover: tmp4oi90o9j.jpg
  credit: tmpcyo196q_.jpg
